print("        _______ ______ _______       _______ _       _______  ______ _     _ ")
print("       (_______|_____ (_______)     (_______|_)     (_______)/ _____|_)   (_)")
print("       | |  ___ _____) )  _   _____ | |      _       _______( (____ | |___| |")
print("       | | (_  |  ____/  | | (_____)| |     | |     |  ___  |\____ \|  ___  |")
print("       | |___) | |       | |        | |_____| |_____| |   | |_____) ) |   | |")
print("        \_____/|_|       |_|         \______)_______)_|   |_(______/|_|   |_|")
print("                                                                             ")                   
print("                                                           Developed By Afnan")
print("                                                 https://github.com/4afnan007")  
print("                                                                             ") 
print("Script is running...                                                         ")
print("                                                                                                              ")
print("Hey, did you hear about the two AI that started talking to each other? look at your browser window maaaaaan...")
print("(ctrl + c) to stop this nonsence") 
print("______________________________________________________________________________________________________________")
print("                                                                                                              ")
